/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubscriptionRouteImport } from './routes/subscription'
import { Route as PointsRouteImport } from './routes/points'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as CreditRouteImport } from './routes/credit'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PromoterIndexRouteImport } from './routes/promoter.index'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as SuperPromotersRouteImport } from './routes/super.promoters'
import { Route as SuperProductsRouteImport } from './routes/super.products'
import { Route as SuperOrdersRouteImport } from './routes/super.orders'
import { Route as SuperCreditRouteImport } from './routes/super.credit'
import { Route as SuperCategoriesRouteImport } from './routes/super.categories'
import { Route as RCodeRouteImport } from './routes/r.$code'
import { Route as PromoterPayoutsRouteImport } from './routes/promoter.payouts'
import { Route as PromoterCommissionsRouteImport } from './routes/promoter.commissions'
import { Route as OrdersOrderIdRouteImport } from './routes/orders.$orderId'
import { Route as CreditPayRouteImport } from './routes/credit.pay'
import { Route as SuperPromotersIndexRouteImport } from './routes/super.promoters.index'
import { Route as SuperPromotersIdRouteImport } from './routes/super.promoters.$id'
import { Route as SuperCreditUserIdRouteImport } from './routes/super.credit.$userId'
import { Route as OrdersOrderIdInvoiceRouteImport } from './routes/orders.$orderId.invoice'

const SubscriptionRoute = SubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const PointsRoute = PointsRouteImport.update({
  id: '/points',
  path: '/points',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditRoute = CreditRouteImport.update({
  id: '/credit',
  path: '/credit',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PromoterIndexRoute = PromoterIndexRouteImport.update({
  id: '/promoter/',
  path: '/promoter/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrdersRoute,
} as any)
const SuperPromotersRoute = SuperPromotersRouteImport.update({
  id: '/super/promoters',
  path: '/super/promoters',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperProductsRoute = SuperProductsRouteImport.update({
  id: '/super/products',
  path: '/super/products',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperOrdersRoute = SuperOrdersRouteImport.update({
  id: '/super/orders',
  path: '/super/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperCreditRoute = SuperCreditRouteImport.update({
  id: '/super/credit',
  path: '/super/credit',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperCategoriesRoute = SuperCategoriesRouteImport.update({
  id: '/super/categories',
  path: '/super/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const RCodeRoute = RCodeRouteImport.update({
  id: '/r/$code',
  path: '/r/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const PromoterPayoutsRoute = PromoterPayoutsRouteImport.update({
  id: '/promoter/payouts',
  path: '/promoter/payouts',
  getParentRoute: () => rootRouteImport,
} as any)
const PromoterCommissionsRoute = PromoterCommissionsRouteImport.update({
  id: '/promoter/commissions',
  path: '/promoter/commissions',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => OrdersRoute,
} as any)
const CreditPayRoute = CreditPayRouteImport.update({
  id: '/pay',
  path: '/pay',
  getParentRoute: () => CreditRoute,
} as any)
const SuperPromotersIndexRoute = SuperPromotersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperPromotersRoute,
} as any)
const SuperPromotersIdRoute = SuperPromotersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SuperPromotersRoute,
} as any)
const SuperCreditUserIdRoute = SuperCreditUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => SuperCreditRoute,
} as any)
const OrdersOrderIdInvoiceRoute = OrdersOrderIdInvoiceRouteImport.update({
  id: '/invoice',
  path: '/invoice',
  getParentRoute: () => OrdersOrderIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/checkout': typeof CheckoutRoute
  '/credit': typeof CreditRouteWithChildren
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRouteWithChildren
  '/points': typeof PointsRoute
  '/subscription': typeof SubscriptionRoute
  '/credit/pay': typeof CreditPayRoute
  '/orders/$orderId': typeof OrdersOrderIdRouteWithChildren
  '/promoter/commissions': typeof PromoterCommissionsRoute
  '/promoter/payouts': typeof PromoterPayoutsRoute
  '/r/$code': typeof RCodeRoute
  '/super/categories': typeof SuperCategoriesRoute
  '/super/credit': typeof SuperCreditRouteWithChildren
  '/super/orders': typeof SuperOrdersRoute
  '/super/products': typeof SuperProductsRoute
  '/super/promoters': typeof SuperPromotersRouteWithChildren
  '/orders/': typeof OrdersIndexRoute
  '/promoter/': typeof PromoterIndexRoute
  '/orders/$orderId/invoice': typeof OrdersOrderIdInvoiceRoute
  '/super/credit/$userId': typeof SuperCreditUserIdRoute
  '/super/promoters/$id': typeof SuperPromotersIdRoute
  '/super/promoters/': typeof SuperPromotersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/checkout': typeof CheckoutRoute
  '/credit': typeof CreditRouteWithChildren
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/points': typeof PointsRoute
  '/subscription': typeof SubscriptionRoute
  '/credit/pay': typeof CreditPayRoute
  '/orders/$orderId': typeof OrdersOrderIdRouteWithChildren
  '/promoter/commissions': typeof PromoterCommissionsRoute
  '/promoter/payouts': typeof PromoterPayoutsRoute
  '/r/$code': typeof RCodeRoute
  '/super/categories': typeof SuperCategoriesRoute
  '/super/credit': typeof SuperCreditRouteWithChildren
  '/super/orders': typeof SuperOrdersRoute
  '/super/products': typeof SuperProductsRoute
  '/orders': typeof OrdersIndexRoute
  '/promoter': typeof PromoterIndexRoute
  '/orders/$orderId/invoice': typeof OrdersOrderIdInvoiceRoute
  '/super/credit/$userId': typeof SuperCreditUserIdRoute
  '/super/promoters/$id': typeof SuperPromotersIdRoute
  '/super/promoters': typeof SuperPromotersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/checkout': typeof CheckoutRoute
  '/credit': typeof CreditRouteWithChildren
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRouteWithChildren
  '/points': typeof PointsRoute
  '/subscription': typeof SubscriptionRoute
  '/credit/pay': typeof CreditPayRoute
  '/orders/$orderId': typeof OrdersOrderIdRouteWithChildren
  '/promoter/commissions': typeof PromoterCommissionsRoute
  '/promoter/payouts': typeof PromoterPayoutsRoute
  '/r/$code': typeof RCodeRoute
  '/super/categories': typeof SuperCategoriesRoute
  '/super/credit': typeof SuperCreditRouteWithChildren
  '/super/orders': typeof SuperOrdersRoute
  '/super/products': typeof SuperProductsRoute
  '/super/promoters': typeof SuperPromotersRouteWithChildren
  '/orders/': typeof OrdersIndexRoute
  '/promoter/': typeof PromoterIndexRoute
  '/orders/$orderId/invoice': typeof OrdersOrderIdInvoiceRoute
  '/super/credit/$userId': typeof SuperCreditUserIdRoute
  '/super/promoters/$id': typeof SuperPromotersIdRoute
  '/super/promoters/': typeof SuperPromotersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catalog'
    | '/checkout'
    | '/credit'
    | '/home'
    | '/login'
    | '/orders'
    | '/points'
    | '/subscription'
    | '/credit/pay'
    | '/orders/$orderId'
    | '/promoter/commissions'
    | '/promoter/payouts'
    | '/r/$code'
    | '/super/categories'
    | '/super/credit'
    | '/super/orders'
    | '/super/products'
    | '/super/promoters'
    | '/orders/'
    | '/promoter/'
    | '/orders/$orderId/invoice'
    | '/super/credit/$userId'
    | '/super/promoters/$id'
    | '/super/promoters/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalog'
    | '/checkout'
    | '/credit'
    | '/home'
    | '/login'
    | '/points'
    | '/subscription'
    | '/credit/pay'
    | '/orders/$orderId'
    | '/promoter/commissions'
    | '/promoter/payouts'
    | '/r/$code'
    | '/super/categories'
    | '/super/credit'
    | '/super/orders'
    | '/super/products'
    | '/orders'
    | '/promoter'
    | '/orders/$orderId/invoice'
    | '/super/credit/$userId'
    | '/super/promoters/$id'
    | '/super/promoters'
  id:
    | '__root__'
    | '/'
    | '/catalog'
    | '/checkout'
    | '/credit'
    | '/home'
    | '/login'
    | '/orders'
    | '/points'
    | '/subscription'
    | '/credit/pay'
    | '/orders/$orderId'
    | '/promoter/commissions'
    | '/promoter/payouts'
    | '/r/$code'
    | '/super/categories'
    | '/super/credit'
    | '/super/orders'
    | '/super/products'
    | '/super/promoters'
    | '/orders/'
    | '/promoter/'
    | '/orders/$orderId/invoice'
    | '/super/credit/$userId'
    | '/super/promoters/$id'
    | '/super/promoters/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogRoute: typeof CatalogRoute
  CheckoutRoute: typeof CheckoutRoute
  CreditRoute: typeof CreditRouteWithChildren
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  OrdersRoute: typeof OrdersRouteWithChildren
  PointsRoute: typeof PointsRoute
  SubscriptionRoute: typeof SubscriptionRoute
  PromoterCommissionsRoute: typeof PromoterCommissionsRoute
  PromoterPayoutsRoute: typeof PromoterPayoutsRoute
  RCodeRoute: typeof RCodeRoute
  SuperCategoriesRoute: typeof SuperCategoriesRoute
  SuperCreditRoute: typeof SuperCreditRouteWithChildren
  SuperOrdersRoute: typeof SuperOrdersRoute
  SuperProductsRoute: typeof SuperProductsRoute
  SuperPromotersRoute: typeof SuperPromotersRouteWithChildren
  PromoterIndexRoute: typeof PromoterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/subscription': {
      id: '/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof SubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/points': {
      id: '/points'
      path: '/points'
      fullPath: '/points'
      preLoaderRoute: typeof PointsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credit': {
      id: '/credit'
      path: '/credit'
      fullPath: '/credit'
      preLoaderRoute: typeof CreditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promoter/': {
      id: '/promoter/'
      path: '/promoter'
      fullPath: '/promoter/'
      preLoaderRoute: typeof PromoterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/super/promoters': {
      id: '/super/promoters'
      path: '/super/promoters'
      fullPath: '/super/promoters'
      preLoaderRoute: typeof SuperPromotersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super/products': {
      id: '/super/products'
      path: '/super/products'
      fullPath: '/super/products'
      preLoaderRoute: typeof SuperProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super/orders': {
      id: '/super/orders'
      path: '/super/orders'
      fullPath: '/super/orders'
      preLoaderRoute: typeof SuperOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super/credit': {
      id: '/super/credit'
      path: '/super/credit'
      fullPath: '/super/credit'
      preLoaderRoute: typeof SuperCreditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super/categories': {
      id: '/super/categories'
      path: '/super/categories'
      fullPath: '/super/categories'
      preLoaderRoute: typeof SuperCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$code': {
      id: '/r/$code'
      path: '/r/$code'
      fullPath: '/r/$code'
      preLoaderRoute: typeof RCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promoter/payouts': {
      id: '/promoter/payouts'
      path: '/promoter/payouts'
      fullPath: '/promoter/payouts'
      preLoaderRoute: typeof PromoterPayoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promoter/commissions': {
      id: '/promoter/commissions'
      path: '/promoter/commissions'
      fullPath: '/promoter/commissions'
      preLoaderRoute: typeof PromoterCommissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/credit/pay': {
      id: '/credit/pay'
      path: '/pay'
      fullPath: '/credit/pay'
      preLoaderRoute: typeof CreditPayRouteImport
      parentRoute: typeof CreditRoute
    }
    '/super/promoters/': {
      id: '/super/promoters/'
      path: '/'
      fullPath: '/super/promoters/'
      preLoaderRoute: typeof SuperPromotersIndexRouteImport
      parentRoute: typeof SuperPromotersRoute
    }
    '/super/promoters/$id': {
      id: '/super/promoters/$id'
      path: '/$id'
      fullPath: '/super/promoters/$id'
      preLoaderRoute: typeof SuperPromotersIdRouteImport
      parentRoute: typeof SuperPromotersRoute
    }
    '/super/credit/$userId': {
      id: '/super/credit/$userId'
      path: '/$userId'
      fullPath: '/super/credit/$userId'
      preLoaderRoute: typeof SuperCreditUserIdRouteImport
      parentRoute: typeof SuperCreditRoute
    }
    '/orders/$orderId/invoice': {
      id: '/orders/$orderId/invoice'
      path: '/invoice'
      fullPath: '/orders/$orderId/invoice'
      preLoaderRoute: typeof OrdersOrderIdInvoiceRouteImport
      parentRoute: typeof OrdersOrderIdRoute
    }
  }
}

interface CreditRouteChildren {
  CreditPayRoute: typeof CreditPayRoute
}

const CreditRouteChildren: CreditRouteChildren = {
  CreditPayRoute: CreditPayRoute,
}

const CreditRouteWithChildren =
  CreditRoute._addFileChildren(CreditRouteChildren)

interface OrdersOrderIdRouteChildren {
  OrdersOrderIdInvoiceRoute: typeof OrdersOrderIdInvoiceRoute
}

const OrdersOrderIdRouteChildren: OrdersOrderIdRouteChildren = {
  OrdersOrderIdInvoiceRoute: OrdersOrderIdInvoiceRoute,
}

const OrdersOrderIdRouteWithChildren = OrdersOrderIdRoute._addFileChildren(
  OrdersOrderIdRouteChildren,
)

interface OrdersRouteChildren {
  OrdersOrderIdRoute: typeof OrdersOrderIdRouteWithChildren
  OrdersIndexRoute: typeof OrdersIndexRoute
}

const OrdersRouteChildren: OrdersRouteChildren = {
  OrdersOrderIdRoute: OrdersOrderIdRouteWithChildren,
  OrdersIndexRoute: OrdersIndexRoute,
}

const OrdersRouteWithChildren =
  OrdersRoute._addFileChildren(OrdersRouteChildren)

interface SuperCreditRouteChildren {
  SuperCreditUserIdRoute: typeof SuperCreditUserIdRoute
}

const SuperCreditRouteChildren: SuperCreditRouteChildren = {
  SuperCreditUserIdRoute: SuperCreditUserIdRoute,
}

const SuperCreditRouteWithChildren = SuperCreditRoute._addFileChildren(
  SuperCreditRouteChildren,
)

interface SuperPromotersRouteChildren {
  SuperPromotersIdRoute: typeof SuperPromotersIdRoute
  SuperPromotersIndexRoute: typeof SuperPromotersIndexRoute
}

const SuperPromotersRouteChildren: SuperPromotersRouteChildren = {
  SuperPromotersIdRoute: SuperPromotersIdRoute,
  SuperPromotersIndexRoute: SuperPromotersIndexRoute,
}

const SuperPromotersRouteWithChildren = SuperPromotersRoute._addFileChildren(
  SuperPromotersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogRoute: CatalogRoute,
  CheckoutRoute: CheckoutRoute,
  CreditRoute: CreditRouteWithChildren,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  OrdersRoute: OrdersRouteWithChildren,
  PointsRoute: PointsRoute,
  SubscriptionRoute: SubscriptionRoute,
  PromoterCommissionsRoute: PromoterCommissionsRoute,
  PromoterPayoutsRoute: PromoterPayoutsRoute,
  RCodeRoute: RCodeRoute,
  SuperCategoriesRoute: SuperCategoriesRoute,
  SuperCreditRoute: SuperCreditRouteWithChildren,
  SuperOrdersRoute: SuperOrdersRoute,
  SuperProductsRoute: SuperProductsRoute,
  SuperPromotersRoute: SuperPromotersRouteWithChildren,
  PromoterIndexRoute: PromoterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
